- name: playbook for file manipulation
  hosts: all
  become: yes
  tasks:
  - name: hello file is copied
    copy: 
      content: "hello from monday evening"
      dest: /tmp/monday.txt
  - name: hi file is copied
    copy: 
      content: "hi there"
      dest: /tmp/monday2.txt
  - name:  archive hh is created
    archive: 
      path: 
      - /tmp/monday.txt
      - /tmp/monday2.txt
      dest: /tmp/hh/zip

    
