- name: playbook for file manipulation
  hosts: all
  become: yes
  tasks:
  - name: hello file is copied
    copy: 
      content: "hello from monday evening"
      dest: /tmp/monday2.txt
  - name: hi file is copied
    copy: 
      content: "Hi here V2"
      dest: /tmp/monday4.txt
  - name: archive hh is created
    archive:
      path:
      - /tmp/monday3.txt
      - /tmp/moday4.txt
      dest: /tmp/hh2.zip
      format: zip